version: "3.3"
services:
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    networks:
      - marketapi-network

  sqlserver_marketapi:
    container_name: sqlserver_marketapi
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass123!Ab"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "11433:1433"
    volumes:
      - .docker/db/data_marketapi/:/var/opt/mssql/data
    networks:
      - marketapi-network

networks:
  marketapi-network:
    driver: bridge
